### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by Thiru-Malai** [geniza-ai/scrapeomatic#14]
I ran this code for a series of usernames. Got this error.

```
results = instagram_scraper.collect(username)
File "\Programs\Python\Python39\lib\site-packages\scrapeomatic\collectors\instagram.py", line 34, in collect
logging.debug(response.json())      
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cgivre** [comment]
@Thiru-Malai 
The reason for this error is likely either that:
* The profile you are pulling is private
* The IP you are using is blocked by Instagram.

**Comment by Thiru-Malai** [comment]
1. I tried using VPN - Didn't work.
2. It's a public profile, I verified it.

**Comment by cgivre** [comment]
@Thiru-Malai Can you share the profile you're trying to access?  My email is charles@geniza.ai, if you'd prefer to email it.  I'd like to take a look.

**Comment by Thiru-Malai** [comment]
Sure I will share it.
Thanks for the help!
